pip install from artifacts - avoid pip install testPyPI

diff --git a/.github/workflows/_MacOS.yml b/.github/workflows/_MacOS.yml
--- a/.github/workflows/_MacOS.yml
+++ b/.github/workflows/_MacOS.yml
@@ -54,6 +54,12 @@ jobs:
           with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
               f.write(f"version={version}\n")
 
+      - name: Download all artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: macos-latest-wheels
+          path: wheels
+
       - name: Install dependencies
         env:
           VERSION: ${{ steps.extract_version.outputs.version }}
@@ -83,31 +89,32 @@ jobs:
           pip install qtconsole==5.6.1
           pip install PyInstaller==6.15.0
           pip install Cython
-          pip install wheel
-          
-          PKG="Pymca_release_test"
-          MAX_TRIES=30
-          SLEEP=20
-          COUNT=1
-          until pip install --no-cache-dir --pre \
-              --index-url https://test.pypi.org/simple/ \
-              --trusted-host test.pypi.org \
-              --only-binary "$PKG" \
-              "$PKG==${VERSION}" || true
-          do
-              if [ $COUNT -ge $MAX_TRIES ]; then
-                  echo "Failed to install $PKG after $MAX_TRIES attempts."
-                  exit 1
-              fi
-      
-              echo "Package not available yet. Attempt $COUNT/$MAX_TRIES failed. Retrying in $SLEEP seconds..."
-              COUNT=$((COUNT+1))
-              sleep $SLEEP
-          done
-          
-          pip install --no-cache-dir --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test==${VERSION}
+          pip install wheel        
+          pip install wheels/     
           pip install --no-build-isolation git+https://github.com/vasole/bcflight.git
           pip install ipywidgets
+          
+#          pip install --no-cache-dir --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test==${VERSION}
+
+#          PKG="Pymca_release_test"
+#          MAX_TRIES=30
+#          SLEEP=20
+#          COUNT=1
+#          until pip install --no-cache-dir --pre \
+#              --index-url https://test.pypi.org/simple/ \
+#              --trusted-host test.pypi.org \
+#              --only-binary "$PKG" \
+#              "$PKG==${VERSION}" || true
+#          do
+#              if [ $COUNT -ge $MAX_TRIES ]; then
+#                  echo "Failed to install $PKG after $MAX_TRIES attempts."
+#                  exit 1
+#              fi
+#
+#              echo "Package not available yet. Attempt $COUNT/$MAX_TRIES failed. Retrying in $SLEEP seconds..."
+#              COUNT=$((COUNT+1))
+#              sleep $SLEEP
+#          done
 
       - name: Build the application for arm64
         run: |
@@ -187,6 +194,12 @@ jobs:
           with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
               f.write(f"version={version}\n")
 
+      - name: Download all artifacts
+        uses: actions/download-artifact@v4
+        with:
+          name: macos-latest-wheels
+          path: wheels
+
       - name: Install dependencies
         env:
           VERSION: ${{ steps.extract_version.outputs.version }}
@@ -218,9 +231,11 @@ jobs:
           arch -x86_64 pip install PyInstaller==6.15.0
           arch -x86_64 pip install Cython
           arch -x86_64 pip install wheel
-          arch -x86_64 pip install --no-cache-dir --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test==${VERSION}
+          arch -x86_64 pip install wheels/
           arch -x86_64 pip install --no-build-isolation git+https://github.com/vasole/bcflight.git
           arch -x86_64 pip install ipywidgets
+
+      #          arch -x86_64 pip install --no-cache-dir --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test==${VERSION}
 
       #          arch -x86_64 pip install PySide6==6.6.0
       #          arch -x86_64 pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/numpy-1.26.2-cp312-cp312-macosx_10_9_universal2.whl
@@ -433,7 +448,7 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: ${{ env.APP_NAME }}-universal-app
-          path: dist/universal/*
+          path: dist/universal2/*
           retention-days: 1
 
       - name: Set app base name (without .app)
diff --git a/.github/workflows/_Wheels.yml b/.github/workflows/_Wheels.yml
--- a/.github/workflows/_Wheels.yml
+++ b/.github/workflows/_Wheels.yml
@@ -671,111 +671,100 @@ jobs:
 
 
 
-  wait_for_testpypi_availability:
-    runs-on: ${{ matrix.os }}
-    needs: upload_to_testpypi
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - os: macos-latest
-            python-version: "3.12"
-            arch: "arch -x86_64"
-            label: "macOS (cp312)"
-          - os: macos-latest
-            python-version: "3.12"
-            arch: "arch -arm64"
-            label: "macOS (cp312)"
-          - os: windows-latest
-            python-version: "3.13"
-            arch: ""
-            label: "Windows (cp313)"
-
-    steps:
-      - uses: actions/checkout@v5
-
-      - name: Set up Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: ${{ matrix.python-version }}
-
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip requests
-
-      - name: Extract version from __init__.py
-        id: extract_version
-        shell: python
-        run: |
-          import os
-          path = 'src/PyMca5/__init__.py'
-
-          version = None
-          with open(path, 'r') as f:
-              for line in f:
-                  if line.startswith('__version__'):
-                      version = line.replace(' ', '').split('=')[-1].strip().strip('"\'')
-                      break
-          assert version is not None, "Version not found in __init__.py"
-          print(version)
-          # Save version to GitHub output
-          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
-              f.write(f"version={version}\n")
-
-      # Yes arch is needed indeed because of PyPI behavior
-      # many times when arm64 download new wheel while x86 got the old one
-      # even after check that wheels exist
-      # and wheels are universal2 for MacOS
-      - name: Wait for wheel availability on TestPyPI
-        env:
-          PACKAGE_NAME: ${{ env.PROJECT_LOWER }}
-          VERSION: ${{ steps.extract_version.outputs.version }}
-        shell: bash
-        run: |
-          pkg="${PACKAGE_NAME}"
-          ver="${VERSION}"
-          max_retries=90
-          delay=10
-          arch_cmd="${{ matrix.arch }}"
-          
-          echo "Python: ${{ matrix.python-version }}, OS: ${{ matrix.os }}"
-               
-          for i in $(seq 1 $max_retries); do
-            echo "Attempt $i/$max_retries..."
-            python -m pip uninstall -y "${pkg}" >/dev/null 2>&1 || true
-
-            if $arch_cmd pip install --no-cache-dir --pre \
-                --extra-index-url https://test.pypi.org/simple/ \
-                --trusted-host test.pypi.org \
-                --only-binary "${pkg}" "${pkg}==${ver}" -q; then
-
-              installed_ver=$(python -c "import importlib.metadata; print(importlib.metadata.version('${pkg}'))" 2>/dev/null || echo "not found")
-
-              if [ "$installed_ver" = "$ver" ]; then
-                echo "✅ Successfully installed ${pkg}==${installed_ver} on ${{ matrix.label }}"
-                exit 0
-              else
-                echo "⚠️ Version mismatch: expected ${ver}, got ${installed_ver}"
-              fi
-            else
-              echo "⏳ Install failed — likely not yet available on TestPyPI."
-            fi
-
-            echo "Waiting ${delay}s before retry..."
-            sleep $delay
-          done
-          
-          echo "Something is wrong. Wheels are not available even after 15min"
-          exit 1
-          
-
+#  wait_for_testpypi_availability:
+#    runs-on: ${{ matrix.os }}
+#    needs: upload_to_testpypi
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - os: macos-latest
+#            python-version: "3.12"
+#            arch: "arch -x86_64"
+#            label: "macOS (cp312)"
+#          - os: macos-latest
+#            python-version: "3.12"
+#            arch: "arch -arm64"
+#            label: "macOS (cp312)"
+#          - os: windows-latest
+#            python-version: "3.13"
+#            arch: ""
+#            label: "Windows (cp313)"
+#
+#    steps:
+#      - uses: actions/checkout@v5
+#
+#      - name: Set up Python
+#        uses: actions/setup-python@v5
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#
+#      - name: Install dependencies
+#        run: |
+#          python -m pip install --upgrade pip requests
+#
+#      - name: Extract version from __init__.py
+#        id: extract_version
+#        shell: python
+#        run: |
+#          import os
+#          path = 'src/PyMca5/__init__.py'
+#
+#          version = None
+#          with open(path, 'r') as f:
+#              for line in f:
+#                  if line.startswith('__version__'):
+#                      version = line.replace(' ', '').split('=')[-1].strip().strip('"\'')
+#                      break
+#          assert version is not None, "Version not found in __init__.py"
+#          print(version)
+#          # Save version to GitHub output
+#          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
+#              f.write(f"version={version}\n")
+#
+#      # Yes arch is needed indeed because of PyPI behavior
+#      # many times when arm64 download new wheel while x86 got the old one
+#      # even after check that wheels exist
+#      # and wheels are universal2 for MacOS
+#      - name: Wait for wheel availability on TestPyPI
+#        env:
+#          PACKAGE_NAME: ${{ env.PROJECT_LOWER }}
+#          VERSION: ${{ steps.extract_version.outputs.version }}
+#        shell: bash
+#        run: |
+#          pkg="${PACKAGE_NAME}"
+#          ver="${VERSION}"
+#          max_retries=90
+#          delay=10
+#          arch_cmd="${{ matrix.arch }}"
+#
+#          echo "Python: ${{ matrix.python-version }}, OS: ${{ matrix.os }}"
+#
 #          for i in $(seq 1 $max_retries); do
 #            echo "Attempt $i/$max_retries..."
-#            if pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple "${pkg}==${ver}" --dry-run >/dev/null 2>&1; then
-#              echo "✅ $pkg==$ver is installable on ${{ matrix.label }}"
-#              exit 0
+#            python -m pip uninstall -y "${pkg}" >/dev/null 2>&1 || true
+#
+#            if $arch_cmd pip install --no-cache-dir --pre \
+#                --extra-index-url https://test.pypi.org/simple/ \
+#                --trusted-host test.pypi.org \
+#                --only-binary "${pkg}" "${pkg}==${ver}" -q; then
+#
+#              installed_ver=$(python -c "import importlib.metadata; print(importlib.metadata.version('${pkg}'))" 2>/dev/null || echo "not found")
+#
+#              if [ "$installed_ver" = "$ver" ]; then
+#                echo "✅ Successfully installed ${pkg}==${installed_ver} on ${{ matrix.label }}"
+#                exit 0
+#              else
+#                echo "⚠️ Version mismatch: expected ${ver}, got ${installed_ver}"
+#              fi
 #            else
-#              echo "⏳ Not yet available. Waiting ${delay}s..."
-#              sleep $delay
+#              echo "⏳ Install failed — likely not yet available on TestPyPI."
 #            fi
+#
+#            echo "Waiting ${delay}s before retry..."
+#            sleep $delay
 #          done
+#
+#          echo "Something is wrong. Wheels are not available even after 15min"
+#          exit 1
+#
