separate x86 and arm for mac

diff --git a/.github/workflows/MacOS.yml b/.github/workflows/MacOS.yml
--- a/.github/workflows/MacOS.yml
+++ b/.github/workflows/MacOS.yml
@@ -10,7 +10,7 @@ env:
 
 jobs:
 # Fat binaries
-  macos11_pyinstaller_python312:
+  macos11_pyinstaller_python312_arm:
     runs-on: macos-latest
     steps:
       - name: Checkout code
@@ -21,11 +21,15 @@ jobs:
         with:
           python-version: "3.12"
 
-      - name: Set environment for 10.9 compatibility
+      - name: Install Rosetta
         run: |
-          echo "MACOSX_DEPLOYMENT_TARGET=10.9" >> $GITHUB_ENV
-          echo "CFLAGS=-mmacosx-version-min=10.9" >> $GITHUB_ENV
-          echo "LDFLAGS=-mmacosx-version-min=10.9" >> $GITHUB_ENV
+          sudo softwareupdate --install-rosetta --agree-to-license
+
+      - name: Set environment for 10.13 compatibility #10.13 is a minimum - setting 10.9 do not actually work
+        run: |
+          echo "MACOSX_DEPLOYMENT_TARGET=10.13" >> $GITHUB_ENV
+          echo "CFLAGS=-mmacosx-version-min=10.13" >> $GITHUB_ENV
+          echo "LDFLAGS=-mmacosx-version-min=10.13" >> $GITHUB_ENV
 
       - name: Install dependencies
         run: |
@@ -58,16 +62,16 @@ jobs:
           pip install --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test
           pip install git+https://github.com/vasole/bcflight.git
 
-      - name: Build with PyInstaller (universal2)
+
+      - name: Build PyInstaller app for arm64
         run: |
-          python build-pyinstaller.py universal2
+          arch -arm64 python build-pyinstaller.py
           ls dist
           find dist/ -type f -perm +111 | while read -r file; do
             version=$(otool -l "$file" 2>/dev/null | awk '/LC_VERSION_MIN_MACOSX/ {show=1} show && /version / {print $2; show=0}' | head -n 1)
             if [ -n "$version" ]; then
               echo "$version  <-  $file"
             fi
-          done | sort
 
       - name: Set app name variable
         run: |
@@ -207,24 +211,139 @@ jobs:
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: macos-pyinstaller-artifacts-dmg
+          name: macos-arm-pyinstaller-artifacts-dmg
           path: dist/*.dmg
           retention-days: 1
-
-#      # also upload to release
-#      - name: Upload dmg to GitHub Release
-#        if: github.event_name == 'release'
-#        uses: softprops/action-gh-release@v1
-#        with:
-#          files: dist/*.dmg
-#        env:
-#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       # upload .app as well
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
-          name: macos-pyinstaller-artifacts-dashdotfix
+          name: macos-arm-pyinstaller-artifacts-dashdotfix
           path: myappfolder/*
           include-hidden-files: true
+          retention-days: 1
+
+  macos11_pyinstaller_python312_x86:
+    runs-on: macos-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v2
+
+      - name: Setup Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: "3.12"
+
+      - name: Install Rosetta
+        run: |
+          sudo softwareupdate --install-rosetta --agree-to-license
+
+      - name: Set environment for 10.13 compatibility #10.13 is a minimum - setting 10.9 do not actually work
+        run: |
+          echo "MACOSX_DEPLOYMENT_TARGET=10.13" >> $GITHUB_ENV
+          echo "CFLAGS=-mmacosx-version-min=10.13" >> $GITHUB_ENV
+          echo "LDFLAGS=-mmacosx-version-min=10.13" >> $GITHUB_ENV
+
+      - name: Install dependencies
+        run: |
+          pip install "setuptools<81"
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/numpy-1.26.2-cp312-cp312-macosx_10_9_universal2.whl
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/h5py-3.10.0-cp312-cp312-macosx_11_0_universal2.whl
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/psutil-5.9.6-cp312-abi3-macosx_10_9_universal2.whl
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/Pillow-10.1.0-cp312-cp312-macosx_11_0_universal2.whl
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/tornado-6.3.3-cp38-abi3-macosx_10_9_universal2.whl
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/contourpy-1.2.0-cp312-cp312-macosx_11_0_universal2.whl
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/kiwisolver-1.4.5-cp312-cp312-macosx_11_0_universal2.whl
+          pip install cycler==0.12.1
+          pip install fonttools==4.45.1
+          pip install packaging==23.2
+          pip install pyparsing==3.1.1
+          pip install python_dateutil==2.8.2
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/matplotlib-3.8.2-cp312-cp312-macosx_11_0_universal2.whl
+          pip install h5py
+          pip install hdf5plugin
+          pip install PySide6==6.6.0
+          pip install lxml==4.9.3
+          pip install --no-cache --trusted-host www.silx.org http://www.silx.org/pub/wheelhouse/universal2/fabio-2023.10.0-cp312-cp312-macosx_10_9_universal2.whl
+          pip install fisx
+          pip install git+https://github.com/silx-kit/silx.git
+          pip install PyOpenGL
+          pip install qtconsole==5.5.1
+          pip install PyInstaller==6.2.0
+          pip install Cython
+          pip install wheel
+          pip install --pre --index-url https://test.pypi.org/simple/ --trusted-host test.pypi.org --only-binary Pymca_release_test Pymca_release_test
+          pip install git+https://github.com/vasole/bcflight.git
+
+
+      - name: Build PyInstaller app for x86_64
+        run: |
+          arch -x86_64 python build-pyinstaller.py
+
+      - name: Set app name variable
+        run: |
+          APP_NAME=$(find dist -maxdepth 1 -name 'PyMca*.app' | head -n 1 | xargs -n 1 basename)
+          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV
+
+      ### dmg test
+
+      - name: Mount the DMG
+        run: |
+          DMG_NAME="${APP_NAME/.app/.dmg}"
+          hdiutil attach "dist/$DMG_NAME" -mountpoint /Volumes/PyMcaApp
+        env:
+          APP_NAME: ${{ env.APP_NAME }}
+
+      - name: Copy .app to /Applications
+        run: |
+          sudo cp -R "/Volumes/PyMcaApp/${{ env.APP_NAME }}" /Applications/
+
+      - name: Make main binary executable
+        run: chmod +x /Applications/${{ env.APP_NAME }}/Contents/MacOS/PyMcaMain
+
+      - name: Run the app to check it launches
+        run: |
+          set -e
+          
+          echo "Launching PyMcaMain..."
+          
+          # Start the app in the background
+          /Applications/${{ env.APP_NAME }}/Contents/MacOS/PyMcaMain &
+          APP_PID=$!
+          
+          echo "App started with PID $APP_PID"
+          
+          # Wait up to 120 seconds for it to crash or hang
+          for i in {1..120}; do
+            if ! ps -p $APP_PID > /dev/null; then
+              echo "App exited early. Checking exit code..."
+              wait $APP_PID
+              EXIT_CODE=$?
+              if [ $EXIT_CODE -ne 0 ]; then
+                echo "App exited with error code $EXIT_CODE"
+                exit $EXIT_CODE
+              else
+                echo "App exited cleanly before 2 minutes."
+                exit 0
+              fi
+            fi
+            sleep 1
+          done
+          
+          echo "App ran for 5 minutes without crashing. Killing it now..."
+          kill $APP_PID || true
+          wait $APP_PID || true
+          echo "App test complete."
+
+      - name: Cleanup
+        run: |
+          sudo rm -rf /Applications/${{ env.APP_NAME }}
+
+      # upload .dmg
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          name: macos-x86(intel)-pyinstaller-artifacts-dmg
+          path: dist/*.dmg
           retention-days: 1
