try to upload in 1 job

diff --git a/.github/workflows/release_test.yml b/.github/workflows/release_test.yml
--- a/.github/workflows/release_test.yml
+++ b/.github/workflows/release_test.yml
@@ -152,62 +152,79 @@ jobs:
           name: ${{ runner.os }}-python${{ matrix.python-version }}-${{ matrix.QT_BINDING }}-dist
           path: dist/*.whl
 
-  upload_to_testpypi:
-    name: Upload all wheels to TestPyPI
-    runs-on: ubuntu-latest
-    needs: build_and_test
-    if: ${{ success() }}
-    steps:
-      - name: Download all artifacts
-        uses: actions/download-artifact@v4
-        with:
-          path: dist-artifacts
-
-      - name: List all downloaded files
-        run: ls -R dist-artifacts
-
-#      - name: Verify package names before upload
-#        run: |
-#          EXPECTED_NAME="Pymca_release_test"
-#          shopt -s nullglob
-#          for file in dist/*.whl; do
-#            if [[ $file == *.whl ]]; then
-#              NAME=$(unzip -p "$file" "*.dist-info/METADATA" | grep ^Name: | awk '{print $2}')
-#            else
-#              NAME=$(tar -xOzf "$file" */PKG-INFO | grep ^Name: | awk '{print $2}')
-#            fi
-#
-#            if [[ "$NAME" != "$EXPECTED_NAME" ]]; then
-#              echo "ERROR: Package name mismatch in $file. Found: $NAME, expected: $EXPECTED_NAME"
-#              exit 1
-#            else
-#              echo "Verified package name: $NAME in $file"
-#            fi
-#          done
-      - name: Upgrade
-        env:
-          TWINE_USERNAME: __token__
-          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
-        run: |
-          python -m pip install --upgrade pip
-          python -m pip install --upgrade setuptools wheel
-          python -m pip install --upgrade twine
-
       - name: Upload wheels to TestPyPI
+        if: runner.os == 'Linux'
         env:
           TWINE_USERNAME: __token__
           TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
         run:
-          python -m twine upload --verbose --repository testpypi dist-artifacts/**/*.whl dist-artifacts/**/*.tar.gz
+          python -m twine upload --verbose --repository testpypi dist/**/*.tar.gz
 
-#      - name: Upload wheels to TestPyPI
-#        if: runner.os != 'Linux'
+      - name: Upload wheels to TestPyPI
+        if: runner.os != 'Linux'
+        env:
+          TWINE_USERNAME: __token__
+          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
+        run: |
+          python -m pip install --upgrade twine
+          python -m twine upload --verbose --repository testpypi dist/**/*.whl
+
+#  upload_to_testpypi:
+#    name: Upload all wheels to TestPyPI
+#    runs-on: ubuntu-latest
+#    needs: build_and_test
+#    if: ${{ success() }}
+#    steps:
+#      - name: Download all artifacts
+#        uses: actions/download-artifact@v4
+#        with:
+#          path: dist-artifacts
+#
+#      - name: List all downloaded files
+#        run: ls -R dist-artifacts
+#
+##      - name: Verify package names before upload
+##        run: |
+##          EXPECTED_NAME="Pymca_release_test"
+##          shopt -s nullglob
+##          for file in dist/*.whl; do
+##            if [[ $file == *.whl ]]; then
+##              NAME=$(unzip -p "$file" "*.dist-info/METADATA" | grep ^Name: | awk '{print $2}')
+##            else
+##              NAME=$(tar -xOzf "$file" */PKG-INFO | grep ^Name: | awk '{print $2}')
+##            fi
+##
+##            if [[ "$NAME" != "$EXPECTED_NAME" ]]; then
+##              echo "ERROR: Package name mismatch in $file. Found: $NAME, expected: $EXPECTED_NAME"
+##              exit 1
+##            else
+##              echo "Verified package name: $NAME in $file"
+##            fi
+##          done
+#      - name: Upgrade
 #        env:
 #          TWINE_USERNAME: __token__
 #          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
 #        run: |
+#          python -m pip install --upgrade pip
+#          python -m pip install --upgrade setuptools wheel
 #          python -m pip install --upgrade twine
-#          python -m twine upload --verbose --repository testpypi dist/*.whl
+#
+#      - name: Upload wheels to TestPyPI
+#        env:
+#          TWINE_USERNAME: __token__
+#          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
+#        run:
+#          python -m twine upload --verbose --repository testpypi dist-artifacts/**/*.whl dist-artifacts/**/*.tar.gz
+#
+##      - name: Upload wheels to TestPyPI
+##        if: runner.os != 'Linux'
+##        env:
+##          TWINE_USERNAME: __token__
+##          TWINE_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
+##        run: |
+##          python -m pip install --upgrade twine
+##          python -m twine upload --verbose --repository testpypi dist/*.whl
         
 
 
