enable other OSs and pythons

diff --git a/.github/workflows/release_test.yml b/.github/workflows/release_test.yml
--- a/.github/workflows/release_test.yml
+++ b/.github/workflows/release_test.yml
@@ -18,26 +18,26 @@ jobs:
       fail-fast: false
       matrix:
         include:
-#          - name-suffix: "(Minimum Versions)"
-#            os: ubuntu-latest
-#            python-version: 3.9
-#            BUILD_COMMAND: --sdist
-#            QT_BINDING: PyQt5==5.14.1
-#            XVFB_RUN: xvfb-run -a
-#
-#          - name-suffix: "PySide6 wheel"
-#            os: ubuntu-latest
-#            python-version: "3.10"
-#            BUILD_COMMAND: --wheel
-#            QT_BINDING: PySide6
-#            XVFB_RUN: xvfb-run -a
+          - name-suffix: "(Minimum Versions)"
+            os: ubuntu-latest
+            python-version: 3.9
+            BUILD_COMMAND: --sdist
+            QT_BINDING: PyQt5==5.14.1
+            XVFB_RUN: xvfb-run -a
 
-#          - name-suffix: "PyQt5 wheel"
-#            os: ubuntu-latest
-#            python-version: "3.10"
-#            BUILD_COMMAND: --wheel
-#            QT_BINDING: PyQt5
-#            XVFB_RUN: xvfb-run -a
+          - name-suffix: "PySide6 wheel"
+            os: ubuntu-latest
+            python-version: "3.10"
+            BUILD_COMMAND: --wheel
+            QT_BINDING: PySide6
+            XVFB_RUN: xvfb-run -a
+
+          - name-suffix: "PyQt5 wheel"
+            os: ubuntu-latest
+            python-version: "3.10"
+            BUILD_COMMAND: --wheel
+            QT_BINDING: PyQt5
+            XVFB_RUN: xvfb-run -a
 
           - name-suffix: "PyQt6 wheel"
             os: macos-latest
@@ -46,26 +46,26 @@ jobs:
             QT_BINDING: PyQt6
             XVFB_RUN: ""
 
-#          - name-suffix: "PyQt6 wheel"
-#            os: windows-latest
-#            python-version: "3.13"
-#            BUILD_COMMAND: --wheel
-#            QT_BINDING: PyQt6
-#            XVFB_RUN: ""
+          - name-suffix: "PyQt6 wheel"
+            os: windows-latest
+            python-version: "3.13"
+            BUILD_COMMAND: --wheel
+            QT_BINDING: PyQt6
+            XVFB_RUN: ""
 
-#          - name-suffix: "PySide6 wheel"
-#            os: windows-latest
-#            python-version: "3.13"
-#            BUILD_COMMAND: --wheel
-#            QT_BINDING: PySide6
-#            XVFB_RUN: ""
-#
-#          - name-suffix: "PySide6 wheel"
-#            os: windows-latest
-#            python-version: "3.9"
-#            BUILD_COMMAND: --wheel
-#            QT_BINDING: PySide6
-#            XVFB_RUN: ""
+          - name-suffix: "PySide6 wheel"
+            os: windows-latest
+            python-version: "3.13"
+            BUILD_COMMAND: --wheel
+            QT_BINDING: PySide6
+            XVFB_RUN: ""
+
+          - name-suffix: "PySide6 wheel"
+            os: windows-latest
+            python-version: "3.9"
+            BUILD_COMMAND: --wheel
+            QT_BINDING: PySide6
+            XVFB_RUN: ""
 
     # Steps represent a sequence of tasks that will be executed as part of the job
     steps:
@@ -145,24 +145,24 @@ jobs:
           name: ${{ runner.os }}-python${{ matrix.python-version }}-${{ matrix.QT_BINDING }}-dist
           path: dist/*
 
-      - name: Verify package names before upload
-        run: |
-          EXPECTED_NAME="Pymca_release_test"
-          shopt -s nullglob
-          for file in dist/*.whl; do
-            if [[ $file == *.whl ]]; then
-              NAME=$(unzip -p "$file" "*.dist-info/METADATA" | grep ^Name: | awk '{print $2}')
-            else
-              NAME=$(tar -xOzf "$file" */PKG-INFO | grep ^Name: | awk '{print $2}')
-            fi
-
-            if [[ "$NAME" != "$EXPECTED_NAME" ]]; then
-              echo "ERROR: Package name mismatch in $file. Found: $NAME, expected: $EXPECTED_NAME"
-              exit 1
-            else
-              echo "Verified package name: $NAME in $file"
-            fi
-          done
+#      - name: Verify package names before upload
+#        run: |
+#          EXPECTED_NAME="Pymca_release_test"
+#          shopt -s nullglob
+#          for file in dist/*.whl; do
+#            if [[ $file == *.whl ]]; then
+#              NAME=$(unzip -p "$file" "*.dist-info/METADATA" | grep ^Name: | awk '{print $2}')
+#            else
+#              NAME=$(tar -xOzf "$file" */PKG-INFO | grep ^Name: | awk '{print $2}')
+#            fi
+#
+#            if [[ "$NAME" != "$EXPECTED_NAME" ]]; then
+#              echo "ERROR: Package name mismatch in $file. Found: $NAME, expected: $EXPECTED_NAME"
+#              exit 1
+#            else
+#              echo "Verified package name: $NAME in $file"
+#            fi
+#          done
 
       - name: Upload wheels to TestPyPI
         env:
@@ -171,7 +171,7 @@ jobs:
         run: |
           python -m pip install --upgrade twine
           python -m twine upload --verbose --repository testpypi dist/*.whl
-#          python -m twine upload --repository testpypi dist/*.tar.gz || true
+          python -m twine upload --repository testpypi dist/*.tar.gz || true
 
       - name: Install
         run: |
